# source('R/spatial_recon_settings.R')
# source('R/spatial_recon_utility.R')
# TumorST <- readr::read_rds("YourPath/TumorBoundary/1.BoundaryDefine/CRC1/TumorSTBoundaryDefine.rds.gz")
# sig_exp <- readr::read_rds("YourPath/sig_exp.rds.gz")
# clustermarkers_list <- readr::read_rds("YourPath/clustermarkers_list.rds.gz")
# DeconData <- oepnxlsx::read.xlsx(system.file("extdata/DeconData.xlsx",package = "Cottrazm"))

#' Title Reconstruct of spatial tumor micro environment at sub-spot level
#'
#' Reconstruct spatial tumor micro environment at sub-spot level using spot deconvolution result and scRNAseq data
#'
#' @param TumorST A seurat object with defined malignant (Mal) spots, boundary (Bdy) spots, and non-malignant (nMal) spots
#' @param sig_exp Mean expression of each feature across cell types generated by scRNAseq data
#' @param clustermarkers_list A list of markers of each cell type  of scRNAseq dataset
#' @param DeconData A data frame of deconvolution result of each spatial spot
#' @param Location Name of location to reconstruct TME.  More spots selected, reconstruct will take longer time.
#'
#' @return A reconstructed Seurat object of ST tumor data
#' @export
#'
#' @examples
#' TumorST <- readr::read_rds("YourPath/TumorBoundary/1.BoundaryDefine/CRC1/TumorSTBoundaryDefine.rds.gz")
#' sig_exp <- readr::read_rds("YourPath/sig_exp.rds.gz")
#' clustermarkers_list <- readr::read_rds("YourPath/clustermarkers_list.rds.gz")
#' DeconData <- oepnxlsx::read.xlsx(system.file("extdata/DeconData.xlsx", package = "Cottrazm"))
#' TumorSTSub <- SpatialRecon(TumorST = TumorST, sig_exp = sig_exp, clustermarkers_list = clustermarkers_list, DeconData = DeconData, Location = "Bdy")
#'
SpatialRecon <- function(TumorST = TumorST,
                         sig_exp = sig_exp,
                         clustermarkers_list = clustermarkers_list,
                         DeconData = DeconData,
                         Location = NULL) {
  if (is.null(Location) == TRUE) {
    Location <- c("Mal", "Bdy", "nMal")
  }

  # get_recons_mtx
  mtx <- get_recon_mtx(
    TumorST = TumorST,
    sig_exp = sig_exp,
    clustermarkers_list = clustermarkers_list,
    DeconData = DeconData,
    Location = Location
  )

  # creat recon seurat object

  TumorSTRecon <- CreateSeuratObject(counts = as.matrix(mtx), project = "TumorSTRecon", assay = "RNA")
  TumorSTRecon@meta.data$Subtypes <- as.data.frame(do.call(rbind, strsplit(rownames(TumorSTRecon@meta.data), split = "_")))$V1
  TumorSTRecon@meta.data$Subtypes <- gsub("\\.", "_", TumorSTRecon@meta.data$Subtypes)
  TumorSTRecon@meta.data$orig.ident <- as.data.frame(do.call(rbind, strsplit(rownames(TumorSTRecon@meta.data), split = "_")))$V2
  TumorSTRecon@meta.data$Location <- TumorST@meta.data$Location[match(TumorSTRecon@meta.data$orig.ident, rownames(TumorST@meta.data))]

  return(TumorSTRecon)
}
