# source('R/recon_spatial_TME_settings.R')
# source('R/recon_spatial_TME_utility.R')
# TumorST <- readr::read_rds("YourPath/Tumorboundary/1.BoundaryDefine/CRC1/TumorSTBoundaryDefine.rds.gz")
# sig_exp <- readr::read_rds("YourPath/sig_exp.rds.gz")
# clustermarkers_list <- readr::read_rds("YourPath/clustermarkers_list.rds.gz")
# DeconData <- read.table(system.file("extdata/DeconData.csv",package = "Cottrazm"),sep = ",",header = T,row.names = "X")

#' Title Reconstruct of spatial tumor micro environment
#'
#' Reconstruct spatial tumor micro environment use spot deconvolution data and scRNAseq data
#'
#' @param TumorST A seurat object with defined tumor spots, boundary/transition zone spots, and out spots
#' @param sig_exp Mean expression of each feature across cell types generated by scRNAseq data
#' @param clustermarkers_list A list of markers of each cell type(major types of scRNAseq dataset)
#' @param DeconData A data frame of deconvolution result of each spatial spot
#' @param Location Name of boundary Location to reconstruct TME.  More spots selected, reconstruct will take longer time.
#'
#' @return A reconstructed seurat object of ST tumor data
#' @export
#'
#' @examples
#' TumorST <- readr::read_rds("YourPath/Tumorboundary/1.BoundaryDefine/CRC1/TumorSTBoundaryDefine.rds.gz")
#' sig_exp <- readr::read_rds("YourPath/sig_exp.rds.gz")
#' clustermarkers_list <- readr::read_rds("YourPath/clustermarkers_list.rds.gz")
#' DeconData <- read.table(system.file("extdata/DeconData.csv",package = "Cottrazm"),sep = ",",header = T,row.names = "X")
#' TumorSTSub <- SpatialRecon(TumorST = TumorST, sig_exp = sig_exp, clustermarkers_list = clustermarkers_list, DeconData = DeconDdata, Location = "Trans")
#'
SpatialRecon <- function(TumorST = TumorST,
                           sig_exp = sig_exp,
                           clustermarkers_list = clustermarkers_list,
                           DeconData = DeconData,
                           Location = c("Tumor","Trans","OutSpots")){

  if (length(Location) == 0)
    Location = c("Tumor","Trans","OutSpots")

  #get_recons_mtx
  mtx <- get_recon_mtx(TumorST = TumorST,
                       sig_exp = sig_exp,
                       clustermarkers_list = clustermarkers_list,
                       DeconData = DeconData,
                       Location = Location)

  #creat recon seurat object

  TumorSTRecon <- CreateSeuratObject(counts = as.matrix(mtx),project = "TumorSTRecon",assay = "RNA")
  TumorSTRecon@meta.data$Subtypes <- as.data.frame(do.call(rbind,strsplit(rownames(TumorSTRecon@meta.data),split = "_")))$V1
  TumorSTRecon@meta.data$Subtypes <- gsub("\\.","_",TumorSTRecon@meta.data$Subtypes)
  TumorSTRecon@meta.data$orig.ident <- as.data.frame(do.call(rbind,strsplit(rownames(TumorSTRecon@meta.data),split = "_")))$V2
  TumorSTRecon@meta.data$Location <- TumorST@meta.data$Location[match(TumorSTRecon@meta.data$orig.ident,rownames(TumorST@meta.data))]

  return(TumorSTRecon)
}
